### ISSUE TITLE
Error returned by get_stamenmap() function

### ISSUE THREAD

**Issue by morepj** [neilfws/earthquakes#2]
I got the following error for the code `NZ.map <- get_stamenmap(bbox = c(163.60840,-49.18170,180,-32.28713) , zoom = 6, maptype = "terrain")`;

> Map from URL : http://tile.stamen.com/terrain/6/61/38.jpg

> Error in readJPEG(tmp) :    JPEG decompression error: Not a JPEG file: starts with 0x89 0x50

Lookup on web shows, the file is PNG but stored with extension jpg.

How to handle this?

Regards,
Prashant

**Comment by neilfws** [comment]
This is [a known issue](https://stackoverflow.com/questions/41066811/error-when-trying-to-use-ggmapget-map-jpeg-decompression-error-not-a-jpeg-f) with the CRAN version of `ggmap`.

The solution is to install the latest version (2.7+) from Github.

```
devtools::install_github("dkahle/ggmap")
```

**Comment by mariagilbert** [comment]
I am having the same issue. I uninstalled ggmap and used the code given by neilfws to reinstall it but I am still getting the same error. Please help. I have an assignment due Friday. I have also tried using a google API and spent hours doing different things to get it to work to no avail. Can someone please describe to me exactly how to uninstall and reinstall ggmap in a way that will give the correct version and not the one with the known error? I am about to cry
